const disabled = true
const docRoot = 'https://docs.aws.amazon.com/lambda/latest/dg/'
export default {
  CreateEventSourceMapping:           { disabled, awsDoc: docRoot + 'API_CreateEventSourceMapping.html' },
  CreateFunctionUrlConfig:            { disabled, awsDoc: docRoot + 'API_CreateFunctionUrlConfig.html' },
  DeleteFunction:                     { disabled, awsDoc: docRoot + 'API_DeleteFunction.html' },
  DeleteFunctionCodeSigningConfig:    { disabled, awsDoc: docRoot + 'API_DeleteFunctionCodeSigningConfig.html' },
  DeleteFunctionEventInvokeConfig:    { disabled, awsDoc: docRoot + 'API_DeleteFunctionEventInvokeConfig.html' },
  DeleteFunctionUrlConfig:            { disabled, awsDoc: docRoot + 'API_DeleteFunctionUrlConfig.html' },
  DeleteLayerVersion:                 { disabled, awsDoc: docRoot + 'API_DeleteLayerVersion.html' },
  DeleteProvisionedConcurrencyConfig: { disabled, awsDoc: docRoot + 'API_DeleteProvisionedConcurrencyConfig.html' },
  InvokeAsync:                        { disabled, awsDoc: docRoot + 'API_InvokeAsync.html' },
  InvokeWithResponseStream:           { disabled, awsDoc: docRoot + 'API_InvokeWithResponseStream.html' },
  ListAliases:                        { disabled, awsDoc: docRoot + 'API_ListAliases.html' },
  ListCodeSigningConfigs:             { disabled, awsDoc: docRoot + 'API_ListCodeSigningConfigs.html' },
  ListEventSourceMappings:            { disabled, awsDoc: docRoot + 'API_ListEventSourceMappings.html' },
  ListFunctionEventInvokeConfigs:     { disabled, awsDoc: docRoot + 'API_ListFunctionEventInvokeConfigs.html' },
  ListFunctions:                      { disabled, awsDoc: docRoot + 'API_ListFunctions.html' },
  ListFunctionsByCodeSigningConfig:   { disabled, awsDoc: docRoot + 'API_ListFunctionsByCodeSigningConfig.html' },
  ListFunctionUrlConfigs:             { disabled, awsDoc: docRoot + 'API_ListFunctionUrlConfigs.html' },
  ListLayers:                         { disabled, awsDoc: docRoot + 'API_ListLayers.html' },
  ListLayerVersions:                  { disabled, awsDoc: docRoot + 'API_ListLayerVersions.html' },
  ListProvisionedConcurrencyConfigs:  { disabled, awsDoc: docRoot + 'API_ListProvisionedConcurrencyConfigs.html' },
  ListTags:                           { disabled, awsDoc: docRoot + 'API_ListTags.html' },
  ListVersionsByFunction:             { disabled, awsDoc: docRoot + 'API_ListVersionsByFunction.html' },
  PublishLayerVersion:                { disabled, awsDoc: docRoot + 'API_PublishLayerVersion.html' },
  PublishVersion:                     { disabled, awsDoc: docRoot + 'API_PublishVersion.html' },
  PutFunctionCodeSigningConfig:       { disabled, awsDoc: docRoot + 'API_PutFunctionCodeSigningConfig.html' },
  PutFunctionEventInvokeConfig:       { disabled, awsDoc: docRoot + 'API_PutFunctionEventInvokeConfig.html' },
  PutProvisionedConcurrencyConfig:    { disabled, awsDoc: docRoot + 'API_PutProvisionedConcurrencyConfig.html' },
  PutRuntimeManagementConfig:         { disabled, awsDoc: docRoot + 'API_PutRuntimeManagementConfig.html' },
  RemoveLayerVersionPermission:       { disabled, awsDoc: docRoot + 'API_RemoveLayerVersionPermission.html' },
  RemovePermission:                   { disabled, awsDoc: docRoot + 'API_RemovePermission.html' },
  TagResource:                        { disabled, awsDoc: docRoot + 'API_TagResource.html' },
  UntagResource:                      { disabled, awsDoc: docRoot + 'API_UntagResource.html' },
  UpdateCodeSigningConfig:            { disabled, awsDoc: docRoot + 'API_UpdateCodeSigningConfig.html' },
  UpdateEventSourceMapping:           { disabled, awsDoc: docRoot + 'API_UpdateEventSourceMapping.html' },
  UpdateFunctionEventInvokeConfig:    { disabled, awsDoc: docRoot + 'API_UpdateFunctionEventInvokeConfig.html' },
  UpdateFunctionUrlConfig:            { disabled, awsDoc: docRoot + 'API_UpdateFunctionUrlConfig.html' },
}
