const disabled = true
const docRoot = 'https://docs.aws.amazon.com/cloudfront/latest/APIReference/'
export default {
  AssociateAlias:                             { disabled, awsDoc: docRoot + 'API_AssociateAlias.html' },
  CopyDistribution:                           { disabled, awsDoc: docRoot + 'API_CopyDistribution.html' },
  CreateDistributionWithTags:                 { disabled, awsDoc: docRoot + 'API_CreateDistributionWithTags.html' },
  CreateFieldLevelEncryptionConfig:           { disabled, awsDoc: docRoot + 'API_CreateFieldLevelEncryptionConfig.html' }, // TODO
  CreateOriginRequestPolicy:                  { disabled, awsDoc: docRoot + 'API_CreateOriginRequestPolicy.html' },
  CreateRealtimeLogConfig:                    { disabled, awsDoc: docRoot + 'API_CreateRealtimeLogConfig.html' },
  CreateResponseHeadersPolicy:                { disabled, awsDoc: docRoot + 'API_CreateResponseHeadersPolicy.html' },
  CreateStreamingDistribution:                { disabled, awsDoc: docRoot + 'API_CreateStreamingDistribution.html' },
  CreateStreamingDistributionWithTags:        { disabled, awsDoc: docRoot + 'API_CreateStreamingDistributionWithTags.html' },
  DeleteFieldLevelEncryptionConfig:           { disabled, awsDoc: docRoot + 'API_DeleteFieldLevelEncryptionConfig.html' },
  DeleteOriginRequestPolicy:                  { disabled, awsDoc: docRoot + 'API_DeleteOriginRequestPolicy.html' },
  DeleteRealtimeLogConfig:                    { disabled, awsDoc: docRoot + 'API_DeleteRealtimeLogConfig.html' },
  DeleteResponseHeadersPolicy:                { disabled, awsDoc: docRoot + 'API_DeleteResponseHeadersPolicy.html' },
  DeleteStreamingDistribution:                { disabled, awsDoc: docRoot + 'API_DeleteStreamingDistribution.html' },
  GetFieldLevelEncryption:                    { disabled, awsDoc: docRoot + 'API_GetFieldLevelEncryption.html' },
  GetFieldLevelEncryptionConfig:              { disabled, awsDoc: docRoot + 'API_GetFieldLevelEncryptionConfig.html' },
  GetInvalidation:                            { disabled, awsDoc: docRoot + 'API_GetInvalidation.html' },
  GetOriginRequestPolicy:                     { disabled, awsDoc: docRoot + 'API_GetOriginRequestPolicy.html' },
  GetOriginRequestPolicyConfig:               { disabled, awsDoc: docRoot + 'API_GetOriginRequestPolicyConfig.html' },
  GetRealtimeLogConfig:                       { disabled, awsDoc: docRoot + 'API_GetRealtimeLogConfig.html' },
  GetResponseHeadersPolicy:                   { disabled, awsDoc: docRoot + 'API_GetResponseHeadersPolicy.html' },
  GetResponseHeadersPolicyConfig:             { disabled, awsDoc: docRoot + 'API_GetResponseHeadersPolicyConfig.html' },
  GetStreamingDistribution:                   { disabled, awsDoc: docRoot + 'API_GetStreamingDistribution.html' },
  GetStreamingDistributionConfig:             { disabled, awsDoc: docRoot + 'API_GetStreamingDistributionConfig.html' },
  ListConflictingAliases:                     { disabled, awsDoc: docRoot + 'API_ListConflictingAliases.html' },
  ListDistributionsByCachePolicyId:           { disabled, awsDoc: docRoot + 'API_ListDistributionsByCachePolicyId.html' },
  ListDistributionsByKeyGroup:                { disabled, awsDoc: docRoot + 'API_ListDistributionsByKeyGroup.html' },
  ListDistributionsByOriginRequestPolicyId:   { disabled, awsDoc: docRoot + 'API_ListDistributionsByOriginRequestPolicyId.html' },
  ListDistributionsByRealtimeLogConfig:       { disabled, awsDoc: docRoot + 'API_ListDistributionsByRealtimeLogConfig.html' },
  ListDistributionsByResponseHeadersPolicyId: { disabled, awsDoc: docRoot + 'API_ListDistributionsByResponseHeadersPolicyId.html' },
  ListDistributionsByWebACLId:                { disabled, awsDoc: docRoot + 'API_ListDistributionsByWebACLId.html' },
  ListFieldLevelEncryptionConfigs:            { disabled, awsDoc: docRoot + 'API_ListFieldLevelEncryptionConfigs.html' },
  ListInvalidations:                          { disabled, awsDoc: docRoot + 'API_ListInvalidations.html' },
  ListOriginRequestPolicies:                  { disabled, awsDoc: docRoot + 'API_ListOriginRequestPolicies.html' },
  ListRealtimeLogConfigs:                     { disabled, awsDoc: docRoot + 'API_ListRealtimeLogConfigs.html' },
  ListResponseHeadersPolicies:                { disabled, awsDoc: docRoot + 'API_ListResponseHeadersPolicies.html' },
  ListStreamingDistributions:                 { disabled, awsDoc: docRoot + 'API_ListStreamingDistributions.html' },
  ListTagsForResource:                        { disabled, awsDoc: docRoot + 'API_ListTagsForResource.html' },
  PublishFunction:                            { disabled, awsDoc: docRoot + 'API_PublishFunction.html' },
  TagResource:                                { disabled, awsDoc: docRoot + 'API_TagResource.html' },
  UntagResource:                              { disabled, awsDoc: docRoot + 'API_UntagResource.html' },
  UpdateDistributionWithStagingConfig:        { disabled, awsDoc: docRoot + 'API_UpdateDistributionWithStagingConfig.html' },
  UpdateFieldLevelEncryptionConfig:           { disabled, awsDoc: docRoot + 'API_UpdateFieldLevelEncryptionConfig.html' },
  UpdateOriginRequestPolicy:                  { disabled, awsDoc: docRoot + 'API_UpdateOriginRequestPolicy.html' },
  UpdateRealtimeLogConfig:                    { disabled, awsDoc: docRoot + 'API_UpdateRealtimeLogConfig.html' },
  UpdateResponseHeadersPolicy:                { disabled, awsDoc: docRoot + 'API_UpdateResponseHeadersPolicy.html' },
  UpdateStreamingDistribution:                { disabled, awsDoc: docRoot + 'API_UpdateStreamingDistribution.html' },
}
