// Generated from @aws-sdk/client-sts@3.1136.0 by npm run gen. Do not edit.
// AWS SDK and Smithy declarations: see ../readme.md#attribution.

interface ResponseMetadata {
	/**
	 * The status code of the last HTTP response received for this operation.
	 */
	httpStatusCode?: number;
	/**
	 * A unique identifier for the last request sent for this operation. Often
	 * requested by AWS service teams to aid in debugging.
	 */
	requestId?: string;
	/**
	 * A secondary identifier for the last request sent. Used for debugging.
	 */
	extendedRequestId?: string;
	/**
	 * A tertiary identifier for the last request sent. Used for debugging.
	 */
	cfId?: string;
	/**
	 * The number of times this operation was attempted.
	 */
	attempts?: number;
	/**
	 * The total amount of time (in milliseconds) that was spent waiting between
	 * retry attempts.
	 */
	totalRetryDelay?: number;
}
interface MetadataBearer {
	/**
	 * Metadata pertaining to this request.
	 */
	$metadata: ResponseMetadata;
}
interface AssumedRoleUser {
	/**
	 * <p>A unique identifier that contains the role ID and the role session name of the role that
	 *          is being assumed. The role ID is generated by Amazon Web Services when the role is created.</p>
	 * @public
	 */
	AssumedRoleId: string | undefined;
	/**
	 * <p>The ARN of the temporary security credentials that are returned from the <a>AssumeRole</a> action. For more information about ARNs and how to use them in
	 *          policies, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html">IAM Identifiers</a> in the
	 *             <i>IAM User Guide</i>.</p>
	 * @public
	 */
	Arn: string | undefined;
}
interface Credentials {
	/**
	 * <p>The access key ID that identifies the temporary security credentials.</p>
	 * @public
	 */
	AccessKeyId: string | undefined;
	/**
	 * <p>The secret access key that can be used to sign requests.</p>
	 * @public
	 */
	SecretAccessKey: string | undefined;
	/**
	 * <p>The token that users must pass to the service API to use the temporary
	 *          credentials.</p>
	 * @public
	 */
	SessionToken: string | undefined;
	/**
	 * <p>The date on which the current credentials expire.</p>
	 * @public
	 */
	Expiration: Date | undefined;
}
interface AssumeRoleResponse {
	/**
	 * <p>The temporary security credentials, which include an access key ID, a secret access key,
	 *          and a security (or session) token.</p>
	 *          <note>
	 *             <p>The size of the security token that STS API operations return is not fixed. We
	 *         strongly recommend that you make no assumptions about the maximum size.</p>
	 *          </note>
	 * @public
	 */
	Credentials?: Credentials | undefined;
	/**
	 * <p>The Amazon Resource Name (ARN) and the assumed role ID, which are identifiers that you
	 *          can use to refer to the resulting temporary security credentials. For example, you can
	 *          reference these credentials as a principal in a resource-based policy by using the ARN or
	 *          assumed role ID. The ARN and ID include the <code>RoleSessionName</code> that you specified
	 *          when you called <code>AssumeRole</code>. </p>
	 * @public
	 */
	AssumedRoleUser?: AssumedRoleUser | undefined;
	/**
	 * <p>A percentage value that indicates the packed size of the session policies and session
	 *       tags combined passed in the request. The request fails if the packed size is greater than 100 percent,
	 *       which means the policies and tags exceeded the allowed space.</p>
	 *
	 * @deprecated (since 2026-06-17) Deprecated. Replaced by SessionTokenUtilization.
	 * @public
	 */
	PackedPolicySize?: number | undefined;
	/**
	 * <p>The source identity specified by the principal that is calling the
	 *             <code>AssumeRole</code> operation.</p>
	 *          <p>You can require users to specify a source identity when they assume a role. You do this
	 *          by using the <code>sts:SourceIdentity</code> condition key in a role trust policy. You can
	 *          use source identity information in CloudTrail logs to determine who took actions with a role.
	 *          You can use the <code>aws:SourceIdentity</code> condition key to further control access to
	 *          Amazon Web Services resources based on the value of source identity. For more information about using
	 *          source identity, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_control-access_monitor.html">Monitor and control
	 *             actions taken with assumed roles</a> in the
	 *          <i>IAM User Guide</i>.</p>
	 *          <p>The regex used to validate this parameter is a string of characters consisting of upper-
	 *          and lower-case alphanumeric characters with no spaces. You can also include underscores or
	 *          any of the following characters: =,.@-</p>
	 * @public
	 */
	SourceIdentity?: string | undefined;
	/**
	 * The percentage (0-100) of the maximum allowed session token size that the returned session
	 *     token consumes.
	 * @public
	 */
	SessionTokenUtilization?: number | undefined;
	/**
	 * The size, in bytes, of the session token returned in the Credentials for this response.
	 * @public
	 */
	SessionTokenSize?: number | undefined;
}
interface AssumeRoleWithSAMLResponse {
	/**
	 * <p>The temporary security credentials, which include an access key ID, a secret access key,
	 *          and a security (or session) token.</p>
	 *          <note>
	 *             <p>The size of the security token that STS API operations return is not fixed. We
	 *         strongly recommend that you make no assumptions about the maximum size.</p>
	 *          </note>
	 * @public
	 */
	Credentials?: Credentials | undefined;
	/**
	 * <p>The identifiers for the temporary security credentials that the operation
	 *          returns.</p>
	 * @public
	 */
	AssumedRoleUser?: AssumedRoleUser | undefined;
	/**
	 * <p>A percentage value that indicates the packed size of the session policies and session
	 *       tags combined passed in the request. The request fails if the packed size is greater than 100 percent,
	 *       which means the policies and tags exceeded the allowed space.</p>
	 *
	 * @deprecated (since 2026-06-17) Deprecated. Replaced by SessionTokenUtilization.
	 * @public
	 */
	PackedPolicySize?: number | undefined;
	/**
	 * <p>The value of the <code>NameID</code> element in the <code>Subject</code> element of the
	 *          SAML assertion.</p>
	 * @public
	 */
	Subject?: string | undefined;
	/**
	 * <p> The format of the name ID, as defined by the <code>Format</code> attribute in the
	 *             <code>NameID</code> element of the SAML assertion. Typical examples of the format are
	 *             <code>transient</code> or <code>persistent</code>. </p>
	 *          <p> If the format includes the prefix
	 *             <code>urn:oasis:names:tc:SAML:2.0:nameid-format</code>, that prefix is removed. For
	 *          example, <code>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</code> is returned as
	 *             <code>transient</code>. If the format includes any other prefix, the format is returned
	 *          with no modifications.</p>
	 * @public
	 */
	SubjectType?: string | undefined;
	/**
	 * <p>The value of the <code>Issuer</code> element of the SAML assertion.</p>
	 * @public
	 */
	Issuer?: string | undefined;
	/**
	 * <p> The value of the <code>Recipient</code> attribute of the
	 *             <code>SubjectConfirmationData</code> element of the SAML assertion. </p>
	 * @public
	 */
	Audience?: string | undefined;
	/**
	 * <p>A hash value based on the concatenation of the following:</p>
	 *          <ul>
	 *             <li>
	 *                <p>The <code>Issuer</code> response value.</p>
	 *             </li>
	 *             <li>
	 *                <p>The Amazon Web Services account ID.</p>
	 *             </li>
	 *             <li>
	 *                <p>The friendly name (the last part of the ARN) of the SAML provider in IAM.</p>
	 *             </li>
	 *          </ul>
	 *          <p>The combination of <code>NameQualifier</code> and <code>Subject</code> can be used to
	 *          uniquely identify a user.</p>
	 *          <p>The following pseudocode shows how the hash value is calculated:</p>
	 *          <p>
	 *             <code>BASE64 ( SHA1 ( "https://example.com/saml" + "123456789012" + "/MySAMLIdP" ) )</code>
	 *          </p>
	 * @public
	 */
	NameQualifier?: string | undefined;
	/**
	 * <p>The value in the <code>SourceIdentity</code> attribute in the SAML assertion. The source
	 *          identity value persists across <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html#iam-term-role-chaining">chained role</a>
	 *          sessions.</p>
	 *          <p>You can require users to set a source identity value when they assume a role. You do
	 *          this by using the <code>sts:SourceIdentity</code> condition key in a role trust policy.
	 *          That way, actions that are taken with the role are associated with that user. After the
	 *          source identity is set, the value cannot be changed. It is present in the request for all
	 *          actions that are taken by the role and persists across <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html#id_roles_terms-and-concepts">chained role</a>
	 *          sessions. You can configure your SAML identity provider to use an attribute associated with
	 *          your users, like user name or email, as the source identity when calling
	 *             <code>AssumeRoleWithSAML</code>. You do this by adding an attribute to the SAML
	 *          assertion. For more information about using source identity, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_control-access_monitor.html">Monitor and control
	 *             actions taken with assumed roles</a> in the
	 *          <i>IAM User Guide</i>.</p>
	 *          <p>The regex used to validate this parameter is a string of characters
	 *     consisting of upper- and lower-case alphanumeric characters with no spaces. You can
	 *     also include underscores or any of the following characters: =,.@-</p>
	 * @public
	 */
	SourceIdentity?: string | undefined;
	/**
	 * The percentage (0-100) of the maximum allowed session token size that the returned session
	 *     token consumes.
	 * @public
	 */
	SessionTokenUtilization?: number | undefined;
	/**
	 * The size, in bytes, of the session token returned in the Credentials for this response.
	 * @public
	 */
	SessionTokenSize?: number | undefined;
}
interface AssumeRoleWithWebIdentityResponse {
	/**
	 * <p>The temporary security credentials, which include an access key ID, a secret access key,
	 *          and a security token.</p>
	 *          <note>
	 *             <p>The size of the security token that STS API operations return is not fixed. We
	 *         strongly recommend that you make no assumptions about the maximum size.</p>
	 *          </note>
	 * @public
	 */
	Credentials?: Credentials | undefined;
	/**
	 * <p>The unique user identifier that is returned by the identity provider. This identifier is
	 *          associated with the <code>WebIdentityToken</code> that was submitted with the
	 *             <code>AssumeRoleWithWebIdentity</code> call. The identifier is typically unique to the
	 *          user and the application that acquired the <code>WebIdentityToken</code> (pairwise
	 *          identifier). For OpenID Connect ID tokens, this field contains the value returned by the
	 *          identity provider as the token's <code>sub</code> (Subject) claim. </p>
	 * @public
	 */
	SubjectFromWebIdentityToken?: string | undefined;
	/**
	 * <p>The Amazon Resource Name (ARN) and the assumed role ID, which are identifiers that you
	 *          can use to refer to the resulting temporary security credentials. For example, you can
	 *          reference these credentials as a principal in a resource-based policy by using the ARN or
	 *          assumed role ID. The ARN and ID include the <code>RoleSessionName</code> that you specified
	 *          when you called <code>AssumeRole</code>. </p>
	 * @public
	 */
	AssumedRoleUser?: AssumedRoleUser | undefined;
	/**
	 * <p>A percentage value that indicates the packed size of the session policies and session
	 *       tags combined passed in the request. The request fails if the packed size is greater than 100 percent,
	 *       which means the policies and tags exceeded the allowed space.</p>
	 *
	 * @deprecated (since 2026-06-17) Deprecated. Replaced by SessionTokenUtilization.
	 * @public
	 */
	PackedPolicySize?: number | undefined;
	/**
	 * <p> The issuing authority of the web identity token presented. For OpenID Connect ID
	 *          tokens, this contains the value of the <code>iss</code> field. For OAuth 2.0 access tokens,
	 *          this contains the value of the <code>ProviderId</code> parameter that was passed in the
	 *             <code>AssumeRoleWithWebIdentity</code> request.</p>
	 * @public
	 */
	Provider?: string | undefined;
	/**
	 * <p>The intended audience (also known as client ID) of the web identity token. This is
	 *          traditionally the client identifier issued to the application that requested the web
	 *          identity token.</p>
	 * @public
	 */
	Audience?: string | undefined;
	/**
	 * <p>The value of the source identity that is returned in the JSON web token (JWT) from the
	 *          identity provider.</p>
	 *          <p>You can require users to set a source identity value when they assume a role. You do
	 *          this by using the <code>sts:SourceIdentity</code> condition key in a role trust policy.
	 *          That way, actions that are taken with the role are associated with that user. After the
	 *          source identity is set, the value cannot be changed. It is present in the request for all
	 *          actions that are taken by the role and persists across <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html#id_roles_terms-and-concepts">chained role</a>
	 *          sessions. You can configure your identity provider to use an attribute associated with your
	 *          users, like user name or email, as the source identity when calling
	 *             <code>AssumeRoleWithWebIdentity</code>. You do this by adding a claim to the JSON web
	 *          token. To learn more about OIDC tokens and claims, see <a href="https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html">Using Tokens with User Pools</a> in the <i>Amazon Cognito Developer Guide</i>.
	 *          For more information about using source identity, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_control-access_monitor.html">Monitor and control
	 *             actions taken with assumed roles</a> in the
	 *          <i>IAM User Guide</i>.</p>
	 *          <p>The regex used to validate this parameter is a string of characters
	 *     consisting of upper- and lower-case alphanumeric characters with no spaces. You can
	 *     also include underscores or any of the following characters: =,.@-</p>
	 * @public
	 */
	SourceIdentity?: string | undefined;
	/**
	 * The percentage (0-100) of the maximum allowed session token size that the returned session
	 *     token consumes.
	 * @public
	 */
	SessionTokenUtilization?: number | undefined;
	/**
	 * The size, in bytes, of the session token returned in the Credentials for this response.
	 * @public
	 */
	SessionTokenSize?: number | undefined;
}
interface DecodeAuthorizationMessageResponse {
	/**
	 * <p>The API returns a response with the decoded message.</p>
	 * @public
	 */
	DecodedMessage?: string | undefined;
}
interface GetAccessKeyInfoResponse {
	/**
	 * <p>The number used to identify the Amazon Web Services account.</p>
	 * @public
	 */
	Account?: string | undefined;
}
interface GetCallerIdentityResponse {
	/**
	 * <p>The unique identifier of the calling entity. The exact value depends on the type of
	 *          entity that is making the call. The values returned are those listed in the <b>aws:userid</b> column in the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html#principaltable">Principal
	 *             table</a> found on the <b>Policy Variables</b> reference
	 *          page in the <i>IAM User Guide</i>.</p>
	 * @public
	 */
	UserId?: string | undefined;
	/**
	 * <p>The Amazon Web Services account ID number of the account that owns or contains the calling
	 *          entity.</p>
	 * @public
	 */
	Account?: string | undefined;
	/**
	 * <p>The Amazon Web Services ARN associated with the calling entity.</p>
	 * @public
	 */
	Arn?: string | undefined;
}
interface FederatedUser {
	/**
	 * <p>The string that identifies the federated user associated with the credentials, similar
	 *          to the unique ID of an IAM user.</p>
	 * @public
	 */
	FederatedUserId: string | undefined;
	/**
	 * <p>The ARN that specifies the federated user that is associated with the credentials. For
	 *          more information about ARNs and how to use them in policies, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html">IAM
	 *             Identifiers</a> in the <i>IAM User Guide</i>. </p>
	 * @public
	 */
	Arn: string | undefined;
}
interface GetFederationTokenResponse {
	/**
	 * <p>The temporary security credentials, which include an access key ID, a secret access key,
	 *          and a security (or session) token.</p>
	 *          <note>
	 *             <p>The size of the security token that STS API operations return is not fixed. We
	 *         strongly recommend that you make no assumptions about the maximum size.</p>
	 *          </note>
	 * @public
	 */
	Credentials?: Credentials | undefined;
	/**
	 * <p>Identifiers for the federated user associated with the credentials (such as
	 *             <code>arn:aws:sts::123456789012:federated-user/Bob</code> or
	 *             <code>123456789012:Bob</code>). You can use the federated user's ARN in your
	 *          resource-based policies, such as an Amazon S3 bucket policy. </p>
	 * @public
	 */
	FederatedUser?: FederatedUser | undefined;
	/**
	 * <p>A percentage value that indicates the packed size of the session policies and session
	 *       tags combined passed in the request. The request fails if the packed size is greater than 100 percent,
	 *       which means the policies and tags exceeded the allowed space.</p>
	 *
	 * @deprecated (since 2026-06-17) Deprecated. Replaced by SessionTokenUtilization.
	 * @public
	 */
	PackedPolicySize?: number | undefined;
	/**
	 * The percentage (0-100) of the maximum allowed session token size that the returned session
	 *     token consumes.
	 * @public
	 */
	SessionTokenUtilization?: number | undefined;
	/**
	 * The size, in bytes, of the session token returned in the Credentials for this response.
	 * @public
	 */
	SessionTokenSize?: number | undefined;
}
interface GetSessionTokenResponse {
	/**
	 * <p>The temporary security credentials, which include an access key ID, a secret access key,
	 *          and a security (or session) token.</p>
	 *          <note>
	 *             <p>The size of the security token that STS API operations return is not fixed. We
	 *         strongly recommend that you make no assumptions about the maximum size.</p>
	 *          </note>
	 * @public
	 */
	Credentials?: Credentials | undefined;
	/**
	 * The percentage (0-100) of the maximum allowed session token size that the returned session
	 *     token consumes.
	 * @public
	 */
	SessionTokenUtilization?: number | undefined;
	/**
	 * The size, in bytes, of the session token returned in the Credentials for this response.
	 * @public
	 */
	SessionTokenSize?: number | undefined;
}
/**
 * @public
 *
 * The output of {@link AssumeRoleCommand}.
 */
export interface AssumeRoleCommandOutput extends AssumeRoleResponse, MetadataBearer {
}
/**
 * @public
 *
 * The output of {@link AssumeRoleWithSAMLCommand}.
 */
export interface AssumeRoleWithSAMLCommandOutput extends AssumeRoleWithSAMLResponse, MetadataBearer {
}
/**
 * @public
 *
 * The output of {@link AssumeRoleWithWebIdentityCommand}.
 */
export interface AssumeRoleWithWebIdentityCommandOutput extends AssumeRoleWithWebIdentityResponse, MetadataBearer {
}
/**
 * @public
 *
 * The output of {@link DecodeAuthorizationMessageCommand}.
 */
export interface DecodeAuthorizationMessageCommandOutput extends DecodeAuthorizationMessageResponse, MetadataBearer {
}
/**
 * @public
 *
 * The output of {@link GetAccessKeyInfoCommand}.
 */
export interface GetAccessKeyInfoCommandOutput extends GetAccessKeyInfoResponse, MetadataBearer {
}
/**
 * @public
 *
 * The output of {@link GetCallerIdentityCommand}.
 */
export interface GetCallerIdentityCommandOutput extends GetCallerIdentityResponse, MetadataBearer {
}
/**
 * @public
 *
 * The output of {@link GetFederationTokenCommand}.
 */
export interface GetFederationTokenCommandOutput extends GetFederationTokenResponse, MetadataBearer {
}
/**
 * @public
 *
 * The output of {@link GetSessionTokenCommand}.
 */
export interface GetSessionTokenCommandOutput extends GetSessionTokenResponse, MetadataBearer {
}

export {};
