const disabled = true
const docRoot = 'https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/'
export default {
  BatchDescribeTypeConfigurations:   { disabled, awsDoc: docRoot + 'API_BatchDescribeTypeConfigurations.html' },
  CancelUpdateStack:                 { disabled, awsDoc: docRoot + 'API_CancelUpdateStack.html' },
  ContinueUpdateRollback:            { disabled, awsDoc: docRoot + 'API_ContinueUpdateRollback.html' },
  CreateChangeSet:                   { disabled, awsDoc: docRoot + 'API_CreateChangeSet.html' },
  DeleteChangeSet:                   { disabled, awsDoc: docRoot + 'API_DeleteChangeSet.html' },
  DescribeAccountLimits:             { disabled, awsDoc: docRoot + 'API_DescribeAccountLimits.html' },
  DescribeChangeSet:                 { disabled, awsDoc: docRoot + 'API_DescribeChangeSet.html' },
  DescribeChangeSetHooks:            { disabled, awsDoc: docRoot + 'API_DescribeChangeSetHooks.html' },
  DescribePublisher:                 { disabled, awsDoc: docRoot + 'API_DescribePublisher.html' },
  DescribeStackDriftDetectionStatus: { disabled, awsDoc: docRoot + 'API_DescribeStackDriftDetectionStatus.html' },
  DescribeStackEvents:               { disabled, awsDoc: docRoot + 'API_DescribeStackEvents.html' },
  DescribeStackResource:             { disabled, awsDoc: docRoot + 'API_DescribeStackResource.html' },
  DescribeStackResourceDrifts:       { disabled, awsDoc: docRoot + 'API_DescribeStackResourceDrifts.html' },
  DescribeStackSetOperation:         { disabled, awsDoc: docRoot + 'API_DescribeStackSetOperation.html' },
  DescribeTypeRegistration:          { disabled, awsDoc: docRoot + 'API_DescribeTypeRegistration.html' },
  DetectStackDrift:                  { disabled, awsDoc: docRoot + 'API_DetectStackDrift.html' },
  DetectStackResourceDrift:          { disabled, awsDoc: docRoot + 'API_DetectStackResourceDrift.html' },
  DetectStackSetDrift:               { disabled, awsDoc: docRoot + 'API_DetectStackSetDrift.html' },
  EstimateTemplateCost:              { disabled, awsDoc: docRoot + 'API_EstimateTemplateCost.html' },
  ExecuteChangeSet:                  { disabled, awsDoc: docRoot + 'API_ExecuteChangeSet.html' },
  GetStackPolicy:                    { disabled, awsDoc: docRoot + 'API_GetStackPolicy.html' },
  GetTemplate:                       { disabled, awsDoc: docRoot + 'API_GetTemplate.html' },
  GetTemplateSummary:                { disabled, awsDoc: docRoot + 'API_GetTemplateSummary.html' },
  ImportStacksToStackSet:            { disabled, awsDoc: docRoot + 'API_ImportStacksToStackSet.html' },
  ListChangeSets:                    { disabled, awsDoc: docRoot + 'API_ListChangeSets.html' },
  ListExports:                       { disabled, awsDoc: docRoot + 'API_ListExports.html' },
  ListImports:                       { disabled, awsDoc: docRoot + 'API_ListImports.html' },
  ListStackInstanceResourceDrifts:   { disabled, awsDoc: docRoot + 'API_ListStackInstanceResourceDrifts.html' },
  ListTypeRegistrations:             { disabled, awsDoc: docRoot + 'API_ListTypeRegistrations.html' }, // TODO: test
  ListTypeVersions:                  { disabled, awsDoc: docRoot + 'API_ListTypeVersions.html' },
  PublishType:                       { disabled, awsDoc: docRoot + 'API_PublishType.html' },
  RecordHandlerProgress:             { disabled, awsDoc: docRoot + 'API_RecordHandlerProgress.html' },
  RegisterPublisher:                 { disabled, awsDoc: docRoot + 'API_RegisterPublisher.html' },
  RollbackStack:                     { disabled, awsDoc: docRoot + 'API_RollbackStack.html' },
  SetStackPolicy:                    { disabled, awsDoc: docRoot + 'API_SetStackPolicy.html' },
  SetTypeConfiguration:              { disabled, awsDoc: docRoot + 'API_SetTypeConfiguration.html' },
  SetTypeDefaultVersion:             { disabled, awsDoc: docRoot + 'API_SetTypeDefaultVersion.html' },
  SignalResource:                    { disabled, awsDoc: docRoot + 'API_SignalResource.html' },
  StopStackSetOperation:             { disabled, awsDoc: docRoot + 'API_StopStackSetOperation.html' },
  TestType:                          { disabled, awsDoc: docRoot + 'API_TestType.html' },
  UpdateStackSet:                    { disabled, awsDoc: docRoot + 'API_UpdateStackSet.html' },
  ValidateTemplate:                  { disabled, awsDoc: docRoot + 'API_ValidateTemplate.html' },
}
